# Generated by Django 4.1.7 on 2023-03-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_profile_o=pic.png', upload_to='picture'),
        ),
    ]
