# Generated by Django 4.1.7 on 2023-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='user_pictures'),
        ),
    ]
