# Generated by Django 4.1.7 on 2023-04-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_profile_o=pic.png', upload_to='user_pictures'),
        ),
    ]
