# Generated by Django 4.1.7 on 2023-03-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_bookreview_created_time_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
