# Generated by Django 4.1.7 on 2023-03-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_bookreview_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
